services:
  web:
    build: .
    container_name: FlaskCast
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - flaskcast-data:/app/data
    environment:
      - FLASK_ENV=development
    command: python app.py

volumes:
  flaskcast-data:
